-- MySQL Script generated by MySQL Workbench
-- Tue May 10 19:45:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poo` DEFAULT CHARACTER SET utf8 ;
USE `poo` ;

-- -----------------------------------------------------
-- Table `poo`.`escrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`escrito` (
  `idescrito` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(3) NOT NULL,
  `autor` VARCHAR(45) NULL,
  `num_pag` INT(11) NULL,
  `editorial` VARCHAR(45) NULL,
  `isbn` VARCHAR(16) NULL,
  `periodicidad` VARCHAR(25) NULL,
  `publicacion` INT NULL,
  PRIMARY KEY (`idescrito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poo`.`audiovisual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`audiovisual` (
  `idaudiovisual` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(3) NOT NULL,
  `artista` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `duracion` VARCHAR(45) NULL,
  `canciones` INT(11) NULL,
  `director` VARCHAR(45) NULL,
  PRIMARY KEY (`idaudiovisual`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poo`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`material` (
  `codigo` VARCHAR(8) NOT NULL,
  `catalogacion` VARCHAR(45) NOT NULL,
  `cantidad_total` INT(11) NOT NULL,
  `cantidad_disponible` INT(11) NOT NULL,
  `tiempo` INT NOT NULL,
  `idescrito` INT(11) NULL,
  `idaudiovisual` INT(11) NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_material_escrito1_idx` (`idescrito` ASC),
  INDEX `fk_material_audiovisual1_idx` (`idaudiovisual` ASC),
  UNIQUE INDEX `idescrito_UNIQUE` (`idescrito` ASC),
  UNIQUE INDEX `idaudiovisual_UNIQUE` (`idaudiovisual` ASC),
  CONSTRAINT `fk_material_escrito1`
    FOREIGN KEY (`idescrito`)
    REFERENCES `poo`.`escrito` (`idescrito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_material_audiovisual1`
    FOREIGN KEY (`idaudiovisual`)
    REFERENCES `poo`.`audiovisual` (`idaudiovisual`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(11) NOT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `nivel` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poo`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`reserva` (
  `idreserva` INT NOT NULL,
  `fechareserva` DATE NULL,
  `estado` VARCHAR(11) NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idreserva`, `codigo`, `idusuario`),
  INDEX `fk_reserva_material1_idx` (`codigo` ASC),
  INDEX `fk_reserva_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_reserva_material1`
    FOREIGN KEY (`codigo`)
    REFERENCES `poo`.`material` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `poo`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poo`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`prestamos` (
  `idprestamo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaprestamo` DATE NULL DEFAULT NULL,
  `fechaentrega` DATE NULL,
  `mora` DECIMAL(4) NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `idsocio` INT(11) NOT NULL,
  `idreserva` INT NULL,
  PRIMARY KEY (`idprestamo`, `codigo`, `idsocio`),
  INDEX `fk_Prestamos_Socio` (`idsocio` ASC),
  INDEX `fk_prestamos_Material1_idx` (`codigo` ASC),
  INDEX `fk_prestamos_reserva2_idx` (`idreserva` ASC),
  CONSTRAINT `fk_Prestamos_Socio`
    FOREIGN KEY (`idsocio`)
    REFERENCES `poo`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prestamos_Material1`
    FOREIGN KEY (`codigo`)
    REFERENCES `poo`.`material` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prestamos_reserva1`
    FOREIGN KEY (`idreserva`)
    REFERENCES `poo`.`reserva` (`idreserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poo`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poo`.`config` (
  `idconfig` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `valor` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconfig`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
