/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Utilidades.ParametrosGlobales;
import java.awt.BorderLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
/**
 *
 * @author amgoo
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    
    int LX;
    int LY;
    int vp0=1;
    int vp1=1;
    int vp2=1;
    LocalDateTime now = LocalDateTime.now();
    public JFPrincipal() {
        initComponents();
        setLocationWindow();
        jDateLogin.setText(now.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        jGlobalUsuario.setText(ParametrosGlobales.GlobalUser);
        jPMenuUsuario.setVisible(false);
        jPSetPanel.setVisible(false);
        //jMenuOptionMT.setVisible(false);
    }
    
    private void setLocationWindow(){
        setLocationRelativeTo(null);
    } 
    private void ShowOption(JPanel p){
        p.setSize(750, 340);
        p.setLocation(0,0);
        jPSetPanel.setVisible(true);
        jPSetPanel.add(p, BorderLayout.CENTER);
        jPSetPanel.removeAll();
        jPSetPanel.add(p);
        jPSetPanel.revalidate();
        jPSetPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenuUsuario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        cerrarPrincipal1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuPanelAd = new javax.swing.JPanel();
        jMenuOptionAD = new javax.swing.JComboBox<>();
        jMenuOptionMT = new javax.swing.JComboBox<>();
        jMenuOptionEX = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jMostrarPanel = new javax.swing.JPanel();
        jLUsuariosIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPMostrar = new javax.swing.JPanel();
        jPSetPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jGlobalUsuario = new javax.swing.JLabel();
        jDateLogin = new javax.swing.JLabel();

        jPMenuUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/AgregarUsuario.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPMenuUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EditarUsuario.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPMenuUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 11, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EliminarUsuario.png"))); // NOI18N
        jPMenuUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/BackUsuarioMenu.png"))); // NOI18N
        jPMenuUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tituloPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        tituloPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/Titulo Bar.png"))); // NOI18N
        tituloPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloPrincipalMouseDragged(evt);
            }
        });
        tituloPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloPrincipalMousePressed(evt);
            }
        });

        cerrarPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/close-app.png"))); // NOI18N
        cerrarPrincipal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarPrincipal1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/minimizar-app.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(cerrarPrincipal1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cerrarPrincipal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING))))
        );

        jMenuPanelAd.setBackground(new java.awt.Color(153, 0, 0));

        jMenuOptionAD.setBackground(new java.awt.Color(255, 0, 0));
        jMenuOptionAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuOptionAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios", "Agregar Usuario", "Modificar Usuario", "Borrar Usuario" }));
        jMenuOptionAD.setPreferredSize(new java.awt.Dimension(130, 21));
        jMenuOptionAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOptionADActionPerformed(evt);
            }
        });

        jMenuOptionMT.setBackground(new java.awt.Color(255, 0, 0));
        jMenuOptionMT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuOptionMT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materiales", "Agregar Material", "Modificar Material", "Borrar Material", "Buscar Material" }));
        jMenuOptionMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOptionMTActionPerformed(evt);
            }
        });

        jMenuOptionEX.setBackground(new java.awt.Color(255, 0, 0));
        jMenuOptionEX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuOptionEX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Existencias", "Ajustar Existencia", "Listar Existencias" }));
        jMenuOptionEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOptionEXActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/HomeIcon.png"))); // NOI18N

        javax.swing.GroupLayout jMenuPanelAdLayout = new javax.swing.GroupLayout(jMenuPanelAd);
        jMenuPanelAd.setLayout(jMenuPanelAdLayout);
        jMenuPanelAdLayout.setHorizontalGroup(
            jMenuPanelAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelAdLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMenuOptionAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jMenuOptionMT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jMenuOptionEX, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMenuPanelAdLayout.setVerticalGroup(
            jMenuPanelAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelAdLayout.createSequentialGroup()
                .addGroup(jMenuPanelAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jMenuPanelAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jMenuOptionAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMenuOptionMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMenuOptionEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMostrarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUsuariosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/UsuariosIcon.png"))); // NOI18N
        jLUsuariosIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLUsuariosIconMouseClicked(evt);
            }
        });
        jMostrarPanel.add(jLUsuariosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuarios");
        jMostrarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, -1));

        jPMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPSetPanelLayout = new javax.swing.GroupLayout(jPSetPanel);
        jPSetPanel.setLayout(jPSetPanelLayout);
        jPSetPanelLayout.setHorizontalGroup(
            jPSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPSetPanelLayout.setVerticalGroup(
            jPSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPMostrar.add(jPSetPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 340));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/PanelBackprincipal.png"))); // NOI18N
        jPMostrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        jMostrarPanel.add(jPMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 750, 340));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/Backprincipal.png"))); // NOI18N
        jMostrarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        jGlobalUsuario.setForeground(new java.awt.Color(153, 153, 153));

        jDateLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDateLogin.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGlobalUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateLogin)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGlobalUsuario)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuPanelAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMostrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jMenuPanelAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jMostrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarPrincipal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarPrincipal1MousePressed
        System.exit(0);
    }//GEN-LAST:event_cerrarPrincipal1MousePressed

    private void tituloPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloPrincipalMousePressed
        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1){
            LX = evt.getX();
            LY = evt.getY();
        }
    }//GEN-LAST:event_tituloPrincipalMousePressed

    private void tituloPrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloPrincipalMouseDragged
        this.setLocation(evt.getXOnScreen()-LX, evt.getYOnScreen()-LY);
    }//GEN-LAST:event_tituloPrincipalMouseDragged

    private void jMenuOptionADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOptionADActionPerformed
//        System.out.println(evt.getID());
//        if (evt.getID() == 1001) {
//            JPMetodos Metodos = new JPMetodos();
//            switch (jMenuOptionAD.getSelectedItem().toString()) {
//                case "Agregar Usuario":
//                    ParametrosGlobales.UsuariosPanelAgregar = true;
//                    ParametrosGlobales.UsuariosPanelModificar = false;
//
//                    if (vp0 == 1) {
//                        jTPMostrar.addTab("Usuarios", Metodos);
//                        jTPMostrar.setSelectedComponent(Metodos);
//
//                    } else if (!"Usuarios".equals(jTPMostrar.getTitleAt(jTPMostrar.getSelectedIndex()))) {
//                        jTPMostrar.setSelectedComponent(Metodos);
//                    }
//                    vp0 = 0;
//                    break;
//                case "Modificar Usuario":
//                    ParametrosGlobales.UsuariosPanelAgregar = false;
//                    ParametrosGlobales.UsuariosPanelModificar = true;
//
//                    if (vp0 == 1) {
//                        jTPMostrar.addTab("Usuarios", Metodos);
//                        jTPMostrar.setSelectedComponent(Metodos);
//
//                    } else if (!"Usuarios".equals(jTPMostrar.getTitleAt(jTPMostrar.getSelectedIndex()))) {
//                        jTPMostrar.setSelectedComponent(Metodos);
//                    }
//                    vp0 = 0;
//                    break;
//                default:
//                    ParametrosGlobales.UsuariosPanelAgregar = false;
//                    ParametrosGlobales.UsuariosPanelModificar = false;
//            }
//        }
    }//GEN-LAST:event_jMenuOptionADActionPerformed

    private void jMenuOptionEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOptionEXActionPerformed
        System.out.println(jMenuOptionEX.getSelectedItem().toString());
    }//GEN-LAST:event_jMenuOptionEXActionPerformed

    private void jMenuOptionMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOptionMTActionPerformed
        System.out.println(jMenuOptionMT.getSelectedItem().toString());
    }//GEN-LAST:event_jMenuOptionMTActionPerformed

    private void jLUsuariosIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLUsuariosIconMouseClicked
        if (jPSetPanel.isVisible()){
            jPSetPanel.setVisible(false);
        }
        if (jPMenuUsuario.isVisible()){
            jPMenuUsuario.setVisible(false);
        }
        else{
            jPMenuUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jLUsuariosIconMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        JPMetodos OpcionUsuario1 = new JPMetodos();
        jPMenuUsuario.setVisible(false);
        ShowOption(OpcionUsuario1);
        ParametrosGlobales.UsuariosPanelAgregar = true;
        ParametrosGlobales.UsuariosPanelModificar = false;
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        JPMetodos OpcionUsuario1 = new JPMetodos();
        jPMenuUsuario.setVisible(false);
        ShowOption(OpcionUsuario1);
        ParametrosGlobales.UsuariosPanelAgregar = false;
        ParametrosGlobales.UsuariosPanelModificar = true;
    }//GEN-LAST:event_jLabel8MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrarPrincipal1;
    private javax.swing.JLabel jDateLogin;
    private javax.swing.JLabel jGlobalUsuario;
    private javax.swing.JLabel jLUsuariosIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMenuOptionAD;
    private javax.swing.JComboBox<String> jMenuOptionEX;
    private javax.swing.JComboBox<String> jMenuOptionMT;
    private javax.swing.JPanel jMenuPanelAd;
    private javax.swing.JPanel jMostrarPanel;
    private javax.swing.JPanel jPMenuUsuario;
    private javax.swing.JPanel jPMostrar;
    private javax.swing.JPanel jPSetPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
