/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Utilidades.ParametrosGlobales;
import java.awt.BorderLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
/**
 *
 * @author amgoo
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    
    int LX;
    int LY;
    int vp0=1;
    int vp1=1;
    int vp2=1;
    LocalDateTime now = LocalDateTime.now();
    public JFPrincipal() {
        initComponents();
        setLocationWindow();
        jDateLogin.setText(now.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        jGlobalUsuario.setText(ParametrosGlobales.GlobalUser);
        jTBUsuario.setVisible(false);
        jPSetPanel.setVisible(false);
        //jMenuOptionMT.setVisible(false);
    }
    
    private void setLocationWindow(){
        setLocationRelativeTo(null);
    } 
    private void ShowOption(JPanel p){
        p.setSize(750, 340);
        p.setLocation(0,0);
        jPSetPanel.setVisible(true);
        jPSetPanel.add(p, BorderLayout.CENTER);
        jPSetPanel.removeAll();
        jPSetPanel.add(p);
        jPSetPanel.revalidate();
        jPSetPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        cerrarPrincipal1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuPanelAd = new javax.swing.JPanel();
        jLIconoHome = new javax.swing.JLabel();
        jTBUsuario = new javax.swing.JToolBar();
        jLIconoAgregarU = new javax.swing.JLabel();
        jLIconoModificarU = new javax.swing.JLabel();
        jLIconoEliminarU = new javax.swing.JLabel();
        jTBMaterial = new javax.swing.JToolBar();
        jLIconoAgregarM = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMostrarPanel = new javax.swing.JPanel();
        jLUsuariosIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPMostrar = new javax.swing.JPanel();
        jPSetPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLMaterialIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jGlobalUsuario = new javax.swing.JLabel();
        jDateLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tituloPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        tituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        tituloPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/Titulo Bar.png"))); // NOI18N
        tituloPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloPrincipalMouseDragged(evt);
            }
        });
        tituloPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloPrincipalMousePressed(evt);
            }
        });

        cerrarPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/close-app.png"))); // NOI18N
        cerrarPrincipal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarPrincipal1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/minimizar-app.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(cerrarPrincipal1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cerrarPrincipal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING))))
        );

        jMenuPanelAd.setBackground(new java.awt.Color(133, 2, 2));

        jLIconoHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIconoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/HomeIcon.png"))); // NOI18N

        jTBUsuario.setFloatable(false);
        jTBUsuario.setRollover(true);

        jLIconoAgregarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/AgregarUsuario.png"))); // NOI18N
        jLIconoAgregarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLIconoAgregarUMouseClicked(evt);
            }
        });
        jTBUsuario.add(jLIconoAgregarU);
        jLIconoAgregarU.getAccessibleContext().setAccessibleName("Agregar");
        jLIconoAgregarU.getAccessibleContext().setAccessibleDescription("Agregar Material");

        jLIconoModificarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EditarUsuario.png"))); // NOI18N
        jLIconoModificarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLIconoModificarUMouseClicked(evt);
            }
        });
        jTBUsuario.add(jLIconoModificarU);
        jLIconoModificarU.getAccessibleContext().setAccessibleName("Editar");
        jLIconoModificarU.getAccessibleContext().setAccessibleDescription("Editar Usuario");

        jLIconoEliminarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EliminarUsuario.png"))); // NOI18N
        jTBUsuario.add(jLIconoEliminarU);
        jLIconoEliminarU.getAccessibleContext().setAccessibleName("Eliminar");
        jLIconoEliminarU.getAccessibleContext().setAccessibleDescription("Eliminar Usuario");

        jTBMaterial.setFloatable(false);
        jTBMaterial.setRollover(true);

        jLIconoAgregarM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/AgregarMaterial.png"))); // NOI18N
        jTBMaterial.add(jLIconoAgregarM);
        jLIconoAgregarM.getAccessibleContext().setAccessibleName("Agregar");
        jLIconoAgregarM.getAccessibleContext().setAccessibleDescription("Agregar Material");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EditarMaterial.png"))); // NOI18N
        jTBMaterial.add(jLabel5);
        jLabel5.getAccessibleContext().setAccessibleName("Editar");
        jLabel5.getAccessibleContext().setAccessibleDescription("Editar Material");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EliminarMaterial.png"))); // NOI18N
        jTBMaterial.add(jLabel7);
        jLabel7.getAccessibleContext().setAccessibleName("Eliminar");
        jLabel7.getAccessibleContext().setAccessibleDescription("Eliminar Material");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/ListarMaterial.png"))); // NOI18N
        jTBMaterial.add(jLabel8);
        jLabel8.getAccessibleContext().setAccessibleName("Listar Disp.");
        jLabel8.getAccessibleContext().setAccessibleDescription("Listar Material");

        javax.swing.GroupLayout jMenuPanelAdLayout = new javax.swing.GroupLayout(jMenuPanelAd);
        jMenuPanelAd.setLayout(jMenuPanelAdLayout);
        jMenuPanelAdLayout.setHorizontalGroup(
            jMenuPanelAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelAdLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLIconoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMenuPanelAdLayout.setVerticalGroup(
            jMenuPanelAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTBUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLIconoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTBMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMostrarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUsuariosIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUsuariosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/UsuariosIcon.png"))); // NOI18N
        jLUsuariosIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLUsuariosIconMouseClicked(evt);
            }
        });
        jMostrarPanel.add(jLUsuariosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuarios");
        jMostrarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        jPMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPSetPanel.setBackground(new java.awt.Color(233, 233, 233));

        javax.swing.GroupLayout jPSetPanelLayout = new javax.swing.GroupLayout(jPSetPanel);
        jPSetPanel.setLayout(jPSetPanelLayout);
        jPSetPanelLayout.setHorizontalGroup(
            jPSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPSetPanelLayout.setVerticalGroup(
            jPSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPMostrar.add(jPSetPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 340));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/PanelBackprincipal.png"))); // NOI18N
        jPMostrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        jMostrarPanel.add(jPMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 750, 340));

        jLMaterialIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMaterialIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/IconoMateriales.png"))); // NOI18N
        jLMaterialIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMaterialIconMouseClicked(evt);
            }
        });
        jMostrarPanel.add(jLMaterialIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Materiales");
        jMostrarPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/Backprincipal.png"))); // NOI18N
        jMostrarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        jGlobalUsuario.setForeground(new java.awt.Color(153, 153, 153));

        jDateLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDateLogin.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGlobalUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateLogin)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGlobalUsuario)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuPanelAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMostrarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jMenuPanelAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jMostrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarPrincipal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarPrincipal1MousePressed
        System.exit(0);
    }//GEN-LAST:event_cerrarPrincipal1MousePressed

    private void tituloPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloPrincipalMousePressed
        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1){
            LX = evt.getX();
            LY = evt.getY();
        }
    }//GEN-LAST:event_tituloPrincipalMousePressed

    private void tituloPrincipalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloPrincipalMouseDragged
        this.setLocation(evt.getXOnScreen()-LX, evt.getYOnScreen()-LY);
    }//GEN-LAST:event_tituloPrincipalMouseDragged

    private void jLUsuariosIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLUsuariosIconMouseClicked
        if (jPSetPanel.isVisible()){
            jPSetPanel.setVisible(false);
        }
        if (jTBUsuario.isVisible()){
            jTBUsuario.setVisible(false);
        }
        else{
            jTBUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jLUsuariosIconMouseClicked

    private void jLIconoAgregarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLIconoAgregarUMouseClicked
        JPMetodos OpcionUsuario1 = new JPMetodos();
        jTBUsuario.setVisible(false);
        ShowOption(OpcionUsuario1);
        ParametrosGlobales.UsuariosPanelAgregar = true;
        ParametrosGlobales.UsuariosPanelModificar = false;
    }//GEN-LAST:event_jLIconoAgregarUMouseClicked

    private void jLIconoModificarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLIconoModificarUMouseClicked
        JPMetodos OpcionUsuario1 = new JPMetodos();
        jTBUsuario.setVisible(false);
        ShowOption(OpcionUsuario1);
        ParametrosGlobales.UsuariosPanelAgregar = false;
        ParametrosGlobales.UsuariosPanelModificar = true;
    }//GEN-LAST:event_jLIconoModificarUMouseClicked

    private void jLMaterialIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMaterialIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLMaterialIconMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrarPrincipal1;
    private javax.swing.JLabel jDateLogin;
    private javax.swing.JLabel jGlobalUsuario;
    private javax.swing.JLabel jLIconoAgregarM;
    private javax.swing.JLabel jLIconoAgregarU;
    private javax.swing.JLabel jLIconoEliminarU;
    private javax.swing.JLabel jLIconoHome;
    private javax.swing.JLabel jLIconoModificarU;
    private javax.swing.JLabel jLMaterialIcon;
    private javax.swing.JLabel jLUsuariosIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jMenuPanelAd;
    private javax.swing.JPanel jMostrarPanel;
    private javax.swing.JPanel jPMostrar;
    private javax.swing.JPanel jPSetPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jTBMaterial;
    private javax.swing.JToolBar jTBUsuario;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
