/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Modelos.PrestamosCRUD;
import Modelos.Validaciones;
import java.util.ArrayList;
import Utilidades.ParametrosGlobales;
/**
 *
 * @author admin
 */
public class Prestamo extends javax.swing.JPanel {
        Validaciones validar;
        PrestamosCRUD prestamo;
    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
        validar = new Validaciones();
        prestamo = new PrestamosCRUD();
        jTableDatos.setModel(prestamo.mostrar(prestamo.SQL_SELECTall));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabeleditorial = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        warning = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        Prestar = new javax.swing.JButton();
        Reservar = new javax.swing.JButton();
        Devolucion = new javax.swing.JButton();
        filtrado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setText("Titulo");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabelAutor.setText("Autor");
        add(jLabelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Libro", "Revista", "CD", "DVD", "Tesis", "Obra" }));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });
        add(ComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel1.setText("Tipo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 102, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 126, -1));

        jLabeleditorial.setText("Editorial");
        add(jLabeleditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        generoLabel.setText("Genero");
        add(generoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 156, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 94, -1));
        add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        Prestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/AgregarMaterial.png"))); // NOI18N
        Prestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestarActionPerformed(evt);
            }
        });
        jToolBar1.add(Prestar);

        Reservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Recursos/EditarMaterial.png"))); // NOI18N
        jToolBar1.add(Reservar);

        Devolucion.setText("DEV");
        jToolBar1.add(Devolucion);

        filtrado.setText("FILTRAR");
        filtrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtradoActionPerformed(evt);
            }
        });
        jToolBar1.add(filtrado);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 218));

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableDatos);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 482, 119));
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
       String item = (String) ComboBoxTipo.getSelectedItem();        
        try{
        switch(item){
            case "Libro":
            labelsNames("Editorial","ISBN");
            jTableDatos.setModel(prestamo.mostrar(prestamo.SQL_SELECTlibros));
            ParametrosGlobales.TipoPrestamo = 1;
                break;
            case "Revista":
            labelsNames("Periodicidad","Año ublicacion");
            jTableDatos.setModel(prestamo.mostrar(prestamo.SQL_SELECTrevista));
            ParametrosGlobales.TipoPrestamo = 2;
                break;
            case "CD":
            labelsNames("Genero","Duracion");
            jTableDatos.setModel(prestamo.mostrar(prestamo.SQL_SELECTcd));
            ParametrosGlobales.TipoPrestamo = 3;
                break;
            case "DVD":
            labelsNames("Genero","Duracion");
            jTableDatos.setModel(prestamo.mostrar(prestamo.SQL_SELECTdvd));
            ParametrosGlobales.TipoPrestamo = 4;
                break;
            case "Tesis":
            

                break;
            case "Obra":
            
                break;
            default:
            jTableDatos.setModel(prestamo.mostrar(prestamo.SQL_SELECTall));    
                break;
        } 
        
        }catch(Exception e){
            System.out.println("error prestamo: " +e);
        }
    }//GEN-LAST:event_ComboBoxTipoActionPerformed
    
    public String agregarSimbolo(String texto){
        String NuevoTexto;
        if(!texto.equals("")){
           return NuevoTexto = "%"+texto+"%"; 
        }else{
            return texto;
        } 
    }
    
    private void filtradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtradoActionPerformed
        String titulo=agregarSimbolo(jTextField1.getText()),
        autor = agregarSimbolo(jTextField2.getText()),
        edit = agregarSimbolo(jTextField3.getText()),
        isbn = agregarSimbolo(jTextField4.getText()),
        periodicidad=edit,publicacion=isbn,
        genero=edit,duracion=isbn;
        
        switch(ParametrosGlobales.TipoPrestamo){
            case 1:
            jTableDatos.setModel(prestamo.Filtrar(prestamo.SQL_BUSCARL,titulo ,autor ,edit ,isbn ));
                break;
            case 2:
            jTableDatos.setModel(prestamo.Filtrar(prestamo.SQL_BUSCARR,titulo ,autor ,periodicidad ,publicacion ));
                break;
            case 3:
            jTableDatos.setModel(prestamo.Filtrar(prestamo.SQL_BUSCARC,titulo ,autor ,genero ,duracion ));   
                break;
            case 4:
            jTableDatos.setModel(prestamo.Filtrar(prestamo.SQL_BUSCARD,titulo ,autor ,genero ,duracion ));   
                break;
        }
        
    }//GEN-LAST:event_filtradoActionPerformed

    private void PrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestarActionPerformed
          prestamo.insertarPrestamo(codigo(),1);//ParametrosGlobales.GlobalAccesNivel
    }//GEN-LAST:event_PrestarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JButton Devolucion;
    private javax.swing.JButton Prestar;
    private javax.swing.JButton Reservar;
    private javax.swing.JButton filtrado;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabeleditorial;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
    public void labelsNames(String nombre1,String nombre2){
        jLabeleditorial.setText(nombre1);
        generoLabel.setText(nombre2); 

    }

    public int getFila(){
        int fila = jTableDatos.getSelectedRow();
        return fila;
    }   
    
    public int getColumna(){
        int columna = jTableDatos.getSelectedColumn();
        return columna;
    } 
    
    public ArrayList getValores(){//obtienen los valores de la fila
        int fila,columna;
        fila = getFila();
        ArrayList valores = new ArrayList();
        for(columna = 1;columna < jTableDatos.getColumnCount();columna++){
        valores.add(jTableDatos.getValueAt(fila, columna));
        }
        return valores;
    }
    
    public Object codigo(){
        Object codigo = null;
        int fila = getFila(),columna = getColumna();
        System.out.println(codigo);
        return codigo = jTableDatos.getValueAt(fila, columna);
    }
}
